spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:28073/minio-client-db
  liquibase:
    changeLog: classpath:/db/db.changelog-master.xml
    databaseChangeLogTable: _databasechangelog
    databaseChangeLogLockTable: _databasechangeloglock
  application:
    name: minio-client
  kafka:
    topic:
      convert-request:
        name: convert-request
      convert-response:
        name: convert-response
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      properties:
        spring:
          json:
            trusted:
              packages: com.mark.convert.core.messaging.domain
      group-id: request_consumer
server:
  port: 8081

minio:
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin123
  bucketName: test-bucket
  filesPath: test_path

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
